services:
  - type: worker
    name: telegram-friend-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY